bundler_args: --without development
language: ruby
rvm:
- jruby
- rbx
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.0
matrix:
  allow_failures:
  - rvm: rbx
  - rvm: jruby
env:
  matrix:
    - secure: PQj7aM9nTSVB3I1qScZp0ZeaJ8CLNZflArOgWtKbifso/r9QQbherR96jk6j0ubRRBbe4emHQv2PGad3Y4B4ATT8gKDeUl/9m4yWt+MfASO5/JHPBxPKZcdvuTRGGYhrc+DmbdVoDWGKmgpNzWilasDYNbVSZWi28HzjImvZyZk=
