bundler_args: --without development
language: ruby
cache: bundler
sudo: false
before_install:
- gem update --system
rvm:
- 2.3.3
env:
  matrix:
    - secure: PQj7aM9nTSVB3I1qScZp0ZeaJ8CLNZflArOgWtKbifso/r9QQbherR96jk6j0ubRRBbe4emHQv2PGad3Y4B4ATT8gKDeUl/9m4yWt+MfASO5/JHPBxPKZcdvuTRGGYhrc+DmbdVoDWGKmgpNzWilasDYNbVSZWi28HzjImvZyZk=
